print('Value: {}'.format(123))
print('Value: {1} {0} {1}'.format(123, 456))

value = 255
print(f'Value: {value}') # Python 3.6.0...
print('Value: {}'.format(value))
print('Value: {0:x}'.format(value))
print('Value: {0:04x}'.format(value))
print('Value: {0:b} {0:o} {0:d} {0:x} {0:X}'.format(value))
value = 1000000000000000
print('Value: {:,}'.format(value)) # Python 3.6.0...
print(f'Value: {value:,}') # Python 3.6.0...
print(f'Value: {value:e}') # Python 3.6.0...
print(f'Value: {value:.2e}') # Python 3.6.0...
value = -100
print('Value: {:+}'.format(value)) # Python 3.6.0...
print(f'Value: {100:+}') # Python 3.6.0...
print(f'Value: {-100:+}') # Python 3.6.0...
value = 6/7
print('Value: {:.1}'.format(value)) # Python 3.6.0...
print('Value: {:.3}'.format(value)) # Python 3.6.0...
print('Value: {:.9}'.format(value)) # Python 3.6.0...
print('Value: {:%}'.format(value)) # Python 3.6.0...
print('Value: {:.0%}'.format(value)) # Python 3.6.0...
print('Value: {:.1%}'.format(value)) # Python 3.6.0...
print('Value: {:.2%}'.format(value)) # Python 3.6.0...


s = 'ABC'
print('{0:<8}'.format(s))
print('{0:>8}'.format(s))
print('{0:^8}'.format(s))
print('{0:米<8}'.format(s))

import datetime
print('{0:%Y-%m-%d %H:%M:%S.%f}'.format(datetime.datetime.now()))
print(f'{datetime.datetime.now():%Y-%m-%d %H:%M:%S.%f}')
