#!/bin/bash
# ----------------------------------------------------------------------------
# 辞書検索
#   $1: 辞書の種類（ej: 英和, je: 和英）
#   $2: 検索キーワード
# 作成日: 2019-02-17
# ----------------------------------------------------------------------------
DictFile() {
    echo "${HOME}/root/db/dictionary/GENE95/gene.LF.utf8.txt"
}
EnJa() {
    grep "${1}" "`DictFile`" -E -A 1 -wi --color=always | less -R -FX
}
JaEn() {
    grep "${1}" "`DictFile`" -E -B 1 -wi --color=always | less -R -FX

}
Run() {
    case "${1}" in
        "ej" ) EnJa "${2}" ;;
        "je" ) JaEn "${2}" ;;
        * ) echo "第一引数は 'ej' 'je' のいずれかにしてください。それぞれ英和、和英です。" ;;
    esac
}
Run "${1}" "${2}"

