#!/bin/bash
# やってみるコマンド。単一ファイルを/tmp/work/y/に配置する
# $1: ext (.py, .sh, .md, .html, .js, .cs, ...)
# $2..: context (cui, gui, http, server)

[ $# -lt 1 ] && { echo "引数不足です。ファイル拡張子をください。"; exit 1; }

pyscript="/tmp/work/Python.TemplateFileMaker.20180314204216/src/do.py"
filepath=`python3 "${pyscript}" "$@"`
if [ -f "$filepath" ]; then
    [ -z "$editor" ] && [ "${editor:-A}" = "${editor-A}" ] && editor='vim'
    "$editor" "$filepath"
fi
